### ISSUE TITLE
Feature request: Support other DB Engines than just MySQL

### ISSUE THREAD

**Issue by willvincent** [fusioncms/fusioncms#337]
Fusion assumes mysql will be used. However, it really ought to support the same DB backends that laravel supports natively; MySQL, Postgres, Sqlite and Sql Server

It's not even possible to get past the install presently unless mysql is available. I personally prefer postgres, and often like using sqlite for local development, neither of which are possible presently.

**Comment by kaidesu** [comment]
Totally - I can see the need to support multiple database drivers. This may pose a bit of a challenge as we do generate tables on the fly. We'll have to do a bit of experimentation to find out what limitations there are between the various drivers that Laravel supports.

Thanks for the issue :+1: Were you able to get FusionCMS set up or did you simply move on due to this issue?

**Comment by kaidesu** [comment]
Closing for now - we may revisit this in the future and add additional database support once the platform is in a stable place.

**Comment by zigmoo** [comment]
> Fusion assumes mysql will be used. However, it really ought to support the same DB backends that laravel supports natively; MySQL, Postgres, Sqlite and Sql Server
> 
> It's not even possible to get past the install presently unless mysql is available. I personally prefer postgres, and often like using sqlite for local development, neither of which are possible presently.

I had the exact _same_ response when first installing Fusion.
