### ISSUE TITLE
Deleting wrong section

### ISSUE THREAD

**Issue by skrolikowski** [fusioncms/fusioncms#721]
### Describe the issue
See screenshot section.

### Expected behavior
Delete the correct section.

### Screenshots
![Jan-29-2021 14-54-10](https://user-images.githubusercontent.com/8143970/106335621-0bc8ba80-6242-11eb-933a-45c1249008c8.gif)

### Version and browser
Version: v6.0.0-beta.10
Browser and version: Chrome (latest)

### Bug report checklist
- [x] I have filled out as much information as I can
- [x] I have detailed how the issue can be reproduced
- [x] I have [searched for existing issues](https://github.com/fusioncms/fusioncms/issues) and to the best of my knowledge this is not a duplicate

**Comment by kaidesu** [comment]
Ah, this has to do with the way we're "splitting" the collection into two - all blueprint sections are contained within a single list, and then we were using a computed property to extract each out separately (body, sidebar). Because of this, the index does not match up 1:1 anymore so we just need to rethink how to display these items in separate lists :v:

**Comment by K-E-L** [comment]
closed by fusioncms/cms#363
